"""Compare server contact positions with evaluated Blender armature skinning.
Input logs/hand-skinning-poses.json is generated by the server-side audit.
"""
import bpy,json,math
from pathlib import Path
from mathutils import Vector,Matrix
ROOT=Path(__file__).resolve().parents[1]
meta=json.loads((ROOT/'game/assets/character_v3.json').read_text())
sheet=json.loads((ROOT/'game/assets/hand_contact_surface_v3.json').read_text())
cases=json.loads((ROOT/'logs/hand-skinning-poses.json').read_text())
rig=bpy.data.objects['CharacterRig'];arm=bpy.data.objects['ArmSkin.R']
C=Matrix(((1,0,0),(0,0,-1),(0,1,0)))
def G(p):return C.transposed()@p
def basis(f,n):return Matrix((f.cross(n),f,n)).transposed()
def place(name,start,finish,normal):
 f=(finish-start).normalized();n=(normal-f*normal.dot(f)).normalized()
 ref=meta['bones'][name];rf=(Vector(ref['tail'])-Vector(ref['head'])).normalized()
 rn=Vector((0,0,1));rn=(rn-rf*rn.dot(rf)).normalized()
 rotation=C@(basis(f,n)@basis(rf,rn).inverted())@C.transposed()
 matrix=(rotation.to_4x4()@rig.data.bones[name].matrix_local)
 matrix.translation=C@start;rig.pose.bones[name].matrix=matrix
 bpy.context.view_layer.update()
def bary(p,a,b,c):
 u=b-a;v=c-a;d=p-a;den=u.dot(u)*v.dot(v)-u.dot(v)**2
 y=(v.dot(v)*d.dot(u)-u.dot(v)*d.dot(v))/den
 z=(u.dot(u)*d.dot(v)-u.dot(v)*d.dot(u))/den
 return (1-y-z,y,z)
arm.data.calc_loop_triangles();triangles=[tuple(t.vertices) for t in arm.data.loop_triangles]
b={k:Vector(v) for k,v in sheet['basis'].items()};rest=[G(v.co) for v in arm.data.vertices]
anchors=[]
for s in sheet['samples']:
 u,a,d=s['local'];p=b['wrist']+b['width']*u+b['finger']*a+b['normal']*d
 ids=triangles[s['triangle']];anchors.append((ids,bary(p,*[rest[i] for i in ids])))
report=[]
for case in cases:
 for bone in rig.pose.bones:bone.matrix_basis=Matrix.Identity(4)
 bpy.context.view_layer.update()
 elbow=Vector(case['pose']['elbow']);wrist=Vector(case['pose']['wrist']);normal=Vector(case['normal']);finger=Vector(case['finger'])
 place('forearm.R',elbow,elbow.lerp(wrist,.5),normal)
 place('forearm_twist.R',elbow.lerp(wrist,.5),wrist,normal)
 place('hand.R',wrist,wrist+finger*.1,normal)
 evaluated=arm.evaluated_get(bpy.context.evaluated_depsgraph_get());mesh=evaluated.to_mesh()
 errors=[]
 for (ids,weights),expected in zip(anchors,case['expected']):
  actual=sum((G(mesh.vertices[i].co)*w for i,w in zip(ids,weights)),Vector())
  errors.append((actual-Vector(expected)).length)
 evaluated.to_mesh_clear();report.append({'maximum_error_m':max(errors),'mean_error_m':sum(errors)/len(errors)})
print(json.dumps(report,indent=2));(ROOT/'logs/contact-skinning-validation.json').write_text(json.dumps(report,indent=2))
assert max(r['maximum_error_m'] for r in report)<.00002,'Contact surface diverges from visible skinning'
print('CONTACT_SKINNING_VALIDATION_PASS')
